### ISSUE TITLE
doesn't respect CR/LF line endings

### ISSUE THREAD

**Issue by hmoffatt** [marcusmueller/include-guard-convert#4]
If you process header files with Windows (CR/LF) line terminations, the line terminations are kept ok but the pragma once is written with LF only.

**Comment by marcusmueller** [comment]
Good bug report. Will think about a way of solving that!

**Comment by marcusmueller** [comment]
Oh, you already did :)

**Comment by marcusmueller** [comment]
merging #5 should solve this, closing. Thank you!
